[package]
name = "message_receiver"
version = "0.1.0"
authors = ["Björn Nyberg <bjorn.nyberg@gmail.com>"]

[dependencies]
nanomsg = "0.6.0"
clap = "2.19.3"

[dependencies.sdl2]
version = "0.28.0"
default-features = false
features = ["ttf"]